# Generated by Django 6.1.1 on 2026-09-16 06:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_event', models.CharField(choices=[('deal.won', 'When Deal is Won'), ('deal.created', 'When Deal is Created'), ('invoice.paid', 'When Invoice is Paid'), ('invoice.overdue', 'When Invoice is Overdue'), ('task.completed', 'When Task is Completed'), ('form.submitted', 'When Form is Submitted'), ('member.joined', 'When New Member Joins')], max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rules', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'celarox_workflow_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_event', models.CharField(max_length=64)),
                ('context_data', models.JSONField(default=dict)),
                ('status', models.CharField(default='success', max_length=32)),
                ('output', models.JSONField(default=dict)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='workflows.workflowrule')),
            ],
            options={
                'db_table': 'celarox_workflow_execution_logs',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('send_email', 'Send Transactional Email via Brevo'), ('create_task', 'Create Follow-up Task'), ('send_notification', 'Send Internal Notification'), ('create_invoice', 'Draft Invoice'), ('webhook', 'Trigger External Webhook')], max_length=64)),
                ('config', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflowrule')),
            ],
            options={
                'db_table': 'celarox_workflow_actions',
                'ordering': ['order'],
            },
        ),
    ]
