"""
Celarox Enterprise Automation & Workflow Execution Engine
"""

import logging
from django.utils import timezone
from .models import WorkflowRule, WorkflowAction, WorkflowExecutionLog
from apps.integrations.brevo_service import send_brevo_email
from apps.projects.models import Project, Task, TaskColumn

logger = logging.getLogger(__name__)


def trigger_workflow_event(workspace_id, trigger_event: str, context_data: dict = None) -> list:
    """
    Find all active rules matching trigger_event in the workspace and execute actions.
    """
    context_data = context_data or {}
    rules = WorkflowRule.objects.filter(
        workspace_id=workspace_id,
        trigger_event=trigger_event,
        is_active=True
    ).prefetch_related('actions')

    results = []

    for rule in rules:
        log_output = {'actions_executed': []}
        rule_status = 'success'

        for action in rule.actions.all():
            try:
                cfg = action.config
                if action.action_type == 'send_email':
                    to_email = cfg.get('to_email') or context_data.get('email')
                    to_name = cfg.get('to_name') or context_data.get('name', 'User')
                    subject = cfg.get('subject', f"Celarox Automation: {rule.name}")
                    body = cfg.get('body', "Automated notification from Celarox Enterprise.")

                    if to_email:
                        res = send_brevo_email(
                            to_email=to_email,
                            to_name=to_name,
                            subject=subject,
                            html_content=f"<div style='font-family: sans-serif; padding: 20px;'>{body}</div>"
                        )
                        log_output['actions_executed'].append({'action': 'send_email', 'status': 'sent', 'to': to_email, 'result': res})

                elif action.action_type == 'create_task':
                    project = Project.objects.filter(workspace_id=workspace_id).first()
                    if project:
                        board = project.boards.first()
                        col = board.columns.first() if board else None
                        task_title = cfg.get('title', f"Follow up: {context_data.get('name', rule.name)}")
                        if col:
                            task = Task.objects.create(
                                workspace_id=workspace_id,
                                project=project,
                                board=board,
                                column=col,
                                title=task_title,
                                description=cfg.get('description', f"Auto-generated by workflow '{rule.name}'")
                            )
                            log_output['actions_executed'].append({'action': 'create_task', 'task_id': str(task.id), 'title': task.title})

            except Exception as exc:
                logger.exception(f"Action execution error: {exc}")
                rule_status = 'partial_failure'
                log_output['actions_executed'].append({'action': action.action_type, 'error': str(exc)})

        # Record log
        WorkflowExecutionLog.objects.create(
            rule=rule,
            trigger_event=trigger_event,
            context_data=context_data,
            status=rule_status,
            output=log_output
        )

        results.append({'rule_id': str(rule.id), 'rule_name': rule.name, 'status': rule_status, 'output': log_output})

    return results
