# Generated by Django 6.1.1 on 2026-09-16 06:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('color', models.CharField(default='#4f46e5', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='documents.documentfolder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_folders', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'celarox_document_folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=1024)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('image', 'Image'), ('doc', 'Word/Document'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('archive', 'ZIP/Archive'), ('other', 'Other')], default='other', max_length=32)),
                ('file_size', models.BigIntegerField(default=0)),
                ('storage_provider', models.CharField(choices=[('cloudinary', 'Cloudinary'), ('google_drive', 'Google Drive'), ('link', 'External Link')], default='cloudinary', max_length=32)),
                ('cloudinary_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('google_drive_id', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_starred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder')),
            ],
            options={
                'db_table': 'celarox_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
