# Generated by Django 4.2.30 on 2026-07-01 07:52

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('products', 'Products'), ('features', 'Features'), ('testimonials', 'Testimonials'), ('contact', 'Contact'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='website/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='website/favicon/')),
                ('site_name', models.CharField(default='Celarox', max_length=255)),
                ('site_description', models.TextField(default='Celarox is a unified business platform that helps organizations launch, manage, and grow from a single connected ecosystem.')),
            ],
            options={
                'verbose_name_plural': 'Website Settings',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('button', 'Button'), ('card', 'Card'), ('heading', 'Heading')], max_length=50)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='core.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
